name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 for Android
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set JAVA_HOME to JDK 17
        run: |
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          java -version

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: ./gradlew build --no-daemon --warning-mode all


